- name:  Demonstrates installing, configuring and deploying web page into nginx web server
  hosts: all
  vars:
    - greeting_msg: DevOps!
    - provisioner_tool: Docker
    - conf_mgnt_tool: Ansible 
  tasks:
  - name: Install nginx web server in Ubuntu
    when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
    apt: name=nginx state=latest update_cache=yes

  - name: Fix the metalink issue in CentOS boxes
    when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
    copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

  - name: Install Extra Packages For Enterprise Linux (EPEL) in CentOS 
    when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
    yum: name=epel-release state=latest 

  - name: Install nginx web server in CentOS 
    when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
    yum: name=nginx state=latest 

  - name: Create custom nginx web root folder
    file: path=/var/html state=directory mode=0777

  - name: Configure nginx web root folder in Ubuntu
    when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
    copy: src=default dest=/etc/nginx/sites-available/default

  - name: Configure nginx web root folder in CentOS 
    when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
    copy: src=default.conf dest=/etc/nginx/conf.d/default.conf

  - name: Retrieve IP Address of containers
    shell: hostname -i
    register: output

  - debug: var=output

  - name: Deploy custom html page into nginx web server
    template: src=index.html.j2 dest=/var/html/index.html

  - name: Restart nginx web server 
    #service: name=nginx state=restarted
    command: service nginx restart
