  - name: Create custom nginx web root folder
    file: path=/var/html state=directory mode=0777

  - name: Retrieve IP Address of containers
    shell: hostname -i
    register: output

  - debug: var=output

  - name: Deploy custom html page into nginx web server
    template: src=index.html.j2 dest=/var/html/index.html

  - name: Restart nginx web server 
    #service: name=nginx state=restarted
    command: service nginx restart
