- name: This playbook will provision ubuntu and centos dockers
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Install Extra Package for Enterprise Linux (EPEL)  
      yum: name=epel-release state=latest

    - name: Install Python Package Installer
      yum: name=python-pip state=latest

    - name: Install docker-py SDK 
      shell: pip install docker-py

    - name: Remove all containers
      shell: docker rm -f $(docker  ps -aq)
      ignore_errors: yes  
  
    - name: Create ubuntu containers
      docker_container:
         docker_host: "tcp://localhost:4243"
         image: "tektutor/ansible-ubuntu"
         name: "ubuntu-{{item}}"
         hostname: "ubuntu-{{item}}"
         state: started
         ports:
           - "2{{item}}:22"
           - "8{{item}}:80"
      with_sequence: start=1 end=2 format=%03d

    - name: Create centos containers
      docker_container:
         docker_host: tcp://localhost:4243
         image: "tektutor/ansible-centos"
         name: "centos-{{item}}"
         hostname: "centos-{{item}}"
         state: started
         ports:
           - "3{{item}}:22"
           - "9{{item}}:80"
      with_sequence: start=1 end=2 format=%03d
