- name: Configure apache web server for custom web root folder in Ubuntu
  copy: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf
  notify:
    - Restart the apache web server in Ubuntu

- name: Grant permission for the custom web root folder in Ubuntu
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf
  notify:
    - Restart the apache web server in Ubuntu
