- name: Demonstrates installing, configuring and deploying web page into nginx web server
  hosts: all
  tasks:
    - name: Install nginx web server in Ubuntu
      apt: name=nginx state=latest update_cache=yes
